import { Question } from "./types";

export const canadaModule: Question[] = [
    {
        id: "ca_hasIrccApplication",
        section: "ca_immigration",
        label: "Avez-vous déjà fait une demande auprès de IRCC (Immigration Canada) dans le passé (visa étude, autre) ?",
        type: "radio",
        required: true,
        options: [
            { value: "YES", label: "Oui" },
            { value: "NO", label: "Non" },
        ],
    },
    {
        id: "ca_irccDetails",
        section: "ca_immigration",
        label: "Veuillez préciser les détails de la demande qui avait été faite auprès de IRCC et la décision de l'agent.",
        type: "textarea",
        required: false,
        condition: [{ questionId: "ca_hasIrccApplication", equals: "YES" }],
    },

    // --- Diploma equivalence label for Canada is WES ---
    {
        id: "ca_diplomaWes",
        section: "academicMain",
        label: "Avez-vous fait une évaluation des études (WES) de ce diplôme ?",
        helpText: "Il s'agit de ce qui est souvent appelé l'équivalence de diplôme",
        type: "radio",
        required: true,
        options: [
            { value: "YES", label: "Oui" },
            { value: "NO", label: "Non" },
            { value: "IN_PROGRESS", label: "En cours" },
        ],
        condition: [{ questionId: "educationLevel", notEquals: "NONE" }],
    },
    {
        id: "ca_diploma2Wes",
        section: "academicSecond",
        label: "Avez-vous fait une évaluation des études (WES) de cet autre diplôme ?",
        helpText: "Il s'agit de ce qui est souvent appelé l'équivalence de diplôme",
        type: "radio",
        required: true,
        options: [
            { value: "YES", label: "Oui" },
            { value: "NO", label: "Non" },
            { value: "IN_PROGRESS", label: "En cours" },
        ],
        condition: [{ questionId: "hasOtherDiploma", equals: "YES" }],
    },

    // --- Language tests ---
    {
        id: "ca_hasFrenchTest",
        section: "language",
        label: "Avez-vous un test de langue française ?",
        type: "radio",
        required: true,
        options: [
            { value: "YES", label: "Oui" },
            { value: "NO", label: "Non" },
        ],
    },
    {
        id: "ca_frenchTestType",
        section: "language",
        label: "Quel test de langue française avez-vous fait ?",
        helpText: "Si vous avez fait plusieurs tests, indiquez celui avec votre meilleur résultat.",
        type: "radio",
        required: true,
        options: [
            { value: "TCF_CANADA", label: "TCF-Canada" },
            { value: "TCF_QUEBEC", label: "TCF-Québec" },
            { value: "TEF_CANADA", label: "TEF-Canada" },
            { value: "TEF_QUEBEC", label: "TEF-Québec / TEFAQ" },
            { value: "OTHER", label: "Autre" },
        ],
        condition: [{ questionId: "ca_hasFrenchTest", equals: "YES" }],
        documentType: "LANGUAGE_REGISTRATION",
    },
    {
        id: "ca_frenchScoreCO",
        section: "language",
        label: "Votre note de compréhension orale (CO) au test de français, telle qu'indiquée sur le certificat",
        placeholder: "Exemple : 587",
        type: "number",
        required: true,
        condition: [{ questionId: "ca_hasFrenchTest", equals: "YES" }],
        max: 699,
    },
    {
        id: "ca_frenchScoreCE",
        section: "language",
        label: "Votre note de compréhension écrite (CE) au test de français",
        placeholder: "Exemple : 587",
        type: "number",
        required: true,
        condition: [{ questionId: "ca_hasFrenchTest", equals: "YES" }],
        max: 699,
    },
    {
        id: "ca_frenchScoreEO",
        section: "language",
        label: "Votre note d'expression orale (EO) au test de français",
        placeholder: "Exemple : 587",
        type: "number",
        required: true,
        condition: [{ questionId: "ca_hasFrenchTest", equals: "YES" }],
        maxFromAnswer: {
            questionId: "ca_frenchTestType",
            map: { TCF_CANADA: 20, TCF_QUEBEC: 20, TEF_CANADA: 699, TEF_QUEBEC: 699 },
        },
    },
    {
        id: "ca_frenchScoreEE",
        section: "language",
        label: "Votre note d'expression écrite (EE) au test de français",
        placeholder: "Exemple : 587",
        type: "number",
        required: true,
        condition: [{ questionId: "ca_hasFrenchTest", equals: "YES" }],
        maxFromAnswer: {
            questionId: "ca_frenchTestType",
            map: { TCF_CANADA: 20, TCF_QUEBEC: 20, TEF_CANADA: 699, TEF_QUEBEC: 699 },
        },
        documentType: "LANGUAGE_RESULT",
    },
    {
        id: "ca_hasEnglishTest",
        section: "language",
        label: "Avez-vous un test de langue anglaise ?",
        type: "radio",
        required: true,
        options: [
            { value: "YES", label: "Oui" },
            { value: "NO", label: "Non" },
        ],
    },
    {
        id: "ca_englishTestType",
        section: "language",
        label: "Quel test de langue anglaise avez-vous fait ?",
        helpText: "Si vous avez fait plusieurs tests, indiquez celui avec votre meilleur résultat.",
        type: "radio",
        required: true,
        options: [
            { value: "IELTS", label: "IELTS" },
            { value: "CELPIP", label: "CELPIP" },
            { value: "OTHER", label: "Autre" },
        ],
        condition: [{ questionId: "ca_hasEnglishTest", equals: "YES" }],
        documentType: "LANGUAGE_REGISTRATION",
    },
    {
        id: "ca_englishScoreListening",
        section: "language",
        label: "Votre note de Listening au test d'anglais",
        placeholder: "Exemple : 6",
        type: "number",
        required: true,
        condition: [{ questionId: "ca_hasEnglishTest", equals: "YES" }],
        maxFromAnswer: { questionId: "ca_englishTestType", map: { IELTS: 9 } },
    },
    {
        id: "ca_englishScoreReading",
        section: "language",
        label: "Votre note de Reading au test d'anglais",
        placeholder: "Exemple : 7",
        type: "number",
        required: true,
        condition: [{ questionId: "ca_hasEnglishTest", equals: "YES" }],
        maxFromAnswer: { questionId: "ca_englishTestType", map: { IELTS: 9 } },
    },
    {
        id: "ca_englishScoreWriting",
        section: "language",
        label: "Votre note de Writing au test d'anglais",
        placeholder: "Exemple : 7",
        type: "number",
        required: true,
        condition: [{ questionId: "ca_hasEnglishTest", equals: "YES" }],
        maxFromAnswer: { questionId: "ca_englishTestType", map: { IELTS: 9 } },
    },
    {
        id: "ca_englishScoreSpeaking",
        section: "language",
        label: "Votre note de Speaking au test d'anglais",
        placeholder: "Exemple : 7",
        type: "number",
        required: true,
        condition: [{ questionId: "ca_hasEnglishTest", equals: "YES" }],
        maxFromAnswer: { questionId: "ca_englishTestType", map: { IELTS: 9 } },
        documentType: "LANGUAGE_RESULT",
    },

    {
        id: "ca_preferredProvince",
        section: "lifeInCountry",
        label: "Dans quelle province/ville aimeriez-vous vivre au Canada ?",
        helpText: "Vous pouvez en citer plusieurs. Exemple : Québec / Ontario / Alberta",
        type: "text",
        required: true,
    },

    // --- Spouse language test (Canada) ---
    {
        id: "ca_spouseLanguageTest",
        section: "spouseLanguage",
        label: "Quel(s) test(s) de langue le conjoint a-t-il ?",
        type: "radio",
        required: true,
        options: [
            { value: "NONE", label: "Aucun test de langue" },
            { value: "TCF_CANADA", label: "TCF-Canada" },
            { value: "TCF_QUEBEC", label: "TCF-Québec" },
            { value: "TEF_CANADA", label: "TEF-Canada" },
            { value: "TEF_QUEBEC", label: "TEF-Québec / TEFAQ" },
            { value: "IELTS", label: "IELTS" },
        ],
        condition: [{ questionId: "maritalStatus", in: ["MARRIED", "COMMON_LAW"] }],
    },
    {
        id: "ca_spouseScoreCO",
        section: "spouseLanguage",
        label: "Sa note de compréhension orale / CO",
        placeholder: "Exemple : 587",
        type: "text",
        required: false,
        condition: [
            { questionId: "maritalStatus", in: ["MARRIED", "COMMON_LAW"] },
            { questionId: "ca_spouseLanguageTest", notEquals: "NONE" },
        ],
    },
    {
        id: "ca_spouseScoreCE",
        section: "spouseLanguage",
        label: "Sa note de compréhension écrite / CE",
        placeholder: "Exemple : 587",
        type: "text",
        required: false,
        condition: [
            { questionId: "maritalStatus", in: ["MARRIED", "COMMON_LAW"] },
            { questionId: "ca_spouseLanguageTest", notEquals: "NONE" },
        ],
    },
    {
        id: "ca_spouseScoreEO",
        section: "spouseLanguage",
        label: "Sa note d'expression orale / EO",
        placeholder: "Exemple : 587",
        type: "text",
        required: false,
        condition: [
            { questionId: "maritalStatus", in: ["MARRIED", "COMMON_LAW"] },
            { questionId: "ca_spouseLanguageTest", notEquals: "NONE" },
        ],
    },
    {
        id: "ca_spouseScoreEE",
        section: "spouseLanguage",
        label: "Sa note d'expression écrite / EE",
        placeholder: "Exemple : 587",
        type: "text",
        required: false,
        condition: [
            { questionId: "maritalStatus", in: ["MARRIED", "COMMON_LAW"] },
            { questionId: "ca_spouseLanguageTest", notEquals: "NONE" },
        ],
    },
];